# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'OCSummary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 # Pods for OCSummary

  pod 'SDWebImage', '~> 4.0'
  pod 'FLAnimatedImage', '~> 1.0'
  pod 'GPUImage'
  pod 'Masonry', '~> 1.1.0'
  pod 'CocoaLumberjack'
  pod 'FBRetainCycleDetector'
  pod 'YYModel'
  pod 'YYCache'
  pod 'YYImage'
  pod 'YYWebImage'
  pod 'YYText'
  pod 'YYKeyboardManager'
  pod 'YYDispatchQueuePool'
  pod 'YYAsyncLayer'
  pod 'YYCategories'
  pod 'AFNetworking', '~> 3.0'
  pod 'FMDB', '~> 2.7.2'
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'IQKeyboardManager' #iOS8 and later
 

end
