# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'OCSummary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 # Pods for OCSummary

  pod 'SDWebImage', '~> 5.0'
  pod 'FLAnimatedImage'
  pod 'GPUImage'
  pod 'Masonry'
  pod 'CocoaLumberjack'
  pod 'FBRetainCycleDetector'
  pod 'YYModel'
  pod 'YYCache'
  pod 'YYImage'
  pod 'YYWebImage'
  pod 'YYText'
  pod 'YYKeyboardManager'
  pod 'YYDispatchQueuePool'
  pod 'YYAsyncLayer'
  pod 'YYCategories'
  pod 'AFNetworking', '~> 4.0'
  pod 'FMDB'
  pod 'MJRefresh'
  pod 'IQKeyboardManager' #iOS8 and later
 

end
